"""initial schema

Revision ID: c9d0506b8fd7
Revises: 
Create Date: 2026-08-26 23:26:43.237720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9d0506b8fd7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinics',
    sa.Column('clinic_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('timing_start', sa.String(length=10), nullable=False),
    sa.Column('timing_end', sa.String(length=10), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('consultation_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('clinic_id')
    )
    op.create_table('otp_codes',
    sa.Column('otp_id', sa.String(length=36), nullable=False),
    sa.Column('mobile', sa.String(length=15), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('otp_id')
    )
    op.create_index(op.f('ix_otp_codes_mobile'), 'otp_codes', ['mobile'], unique=False)
    op.create_table('patients',
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('gender', sa.Enum('M', 'F', 'Other', name='gender', native_enum=False), nullable=False),
    sa.Column('mobile', sa.String(length=15), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('occupation', sa.String(length=100), nullable=False),
    sa.Column('unique_patient_id', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('blood_group', sa.String(length=5), nullable=True),
    sa.Column('emergency_contact', sa.String(length=200), nullable=True),
    sa.Column('allergies', sa.String(length=1000), nullable=True),
    sa.Column('chronic_conditions', sa.String(length=1000), nullable=True),
    sa.Column('referred_by', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('patient_id')
    )
    op.create_index(op.f('ix_patients_full_name'), 'patients', ['full_name'], unique=False)
    op.create_index(op.f('ix_patients_mobile'), 'patients', ['mobile'], unique=False)
    op.create_index(op.f('ix_patients_unique_patient_id'), 'patients', ['unique_patient_id'], unique=True)
    op.create_table('refresh_tokens',
    sa.Column('token_id', sa.String(length=36), nullable=False),
    sa.Column('principal_type', sa.Enum('user', 'patient', name='principal_type', native_enum=False), nullable=False),
    sa.Column('principal_id', sa.String(length=36), nullable=False),
    sa.Column('family_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('token_id')
    )
    op.create_index(op.f('ix_refresh_tokens_family_id'), 'refresh_tokens', ['family_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_principal_id'), 'refresh_tokens', ['principal_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_table('users',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('Receptionist', 'Doctor', 'Patient', 'SuperAdmin', name='user_role', native_enum=False), nullable=False),
    sa.Column('clinic_ids', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('appointments',
    sa.Column('appt_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('doctor_id', sa.String(length=36), nullable=False),
    sa.Column('clinic_id', sa.String(length=36), nullable=False),
    sa.Column('appt_date', sa.Date(), nullable=False),
    sa.Column('appt_time', sa.String(length=10), nullable=False),
    sa.Column('visit_type', sa.Enum('New', 'Follow-Up', 'Walk-In', name='visit_type', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('Scheduled', 'Confirmed', 'Arrived', 'In Consultation', 'Completed', 'No-Show', 'Cancelled', name='appointment_status', native_enum=False), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('cancel_reason', sa.String(length=500), nullable=True),
    sa.Column('token_number', sa.Integer(), nullable=True),
    sa.Column('waiting_started_at', sa.DateTime(), nullable=True),
    sa.Column('consultation_started_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.clinic_id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('appt_id')
    )
    op.create_index(op.f('ix_appointments_appt_date'), 'appointments', ['appt_date'], unique=False)
    op.create_table('audit_logs',
    sa.Column('log_id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', name='audit_action', native_enum=False), nullable=False),
    sa.Column('performed_by', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('changes_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['performed_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('medicines',
    sa.Column('medicine_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('manufacturer', sa.String(length=200), nullable=True),
    sa.Column('batch_number', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('expiry_date', sa.String(length=20), nullable=True),
    sa.Column('low_stock_threshold', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.clinic_id'], ),
    sa.PrimaryKeyConstraint('medicine_id')
    )
    op.create_table('notification_logs',
    sa.Column('notification_id', sa.String(length=36), nullable=False),
    sa.Column('event', sa.String(length=50), nullable=False),
    sa.Column('channel', sa.Enum('SMS', 'WhatsApp', 'Email', name='notif_channel', native_enum=False), nullable=False),
    sa.Column('recipient', sa.String(length=200), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('body', sa.String(length=2000), nullable=False),
    sa.Column('status', sa.Enum('Queued', 'Sent', 'Failed', name='notif_status', native_enum=False), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_index(op.f('ix_notification_logs_created_at'), 'notification_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_notification_logs_event'), 'notification_logs', ['event'], unique=False)
    op.create_table('invoices',
    sa.Column('invoice_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('appt_id', sa.String(length=36), nullable=True),
    sa.Column('consultation_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('medicine_charges', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('misc_charges', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('due_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('Draft', 'Issued', 'Partially Paid', 'Paid', name='invoice_status', native_enum=False), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['appt_id'], ['appointments.appt_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('invoice_id')
    )
    op.create_table('prescriptions',
    sa.Column('prescription_id', sa.String(length=36), nullable=False),
    sa.Column('appt_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('chief_complaint', sa.String(length=2000), nullable=False),
    sa.Column('diagnosis', sa.String(length=1000), nullable=False),
    sa.Column('medicines', sa.JSON(), nullable=False),
    sa.Column('instructions', sa.String(length=2000), nullable=True),
    sa.Column('follow_up_date', sa.Date(), nullable=True),
    sa.Column('is_fee_waived', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['appt_id'], ['appointments.appt_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('prescription_id')
    )
    op.create_table('payments',
    sa.Column('payment_id', sa.String(length=36), nullable=False),
    sa.Column('invoice_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_mode', sa.Enum('Cash', 'Card', 'UPI', 'Online', name='payment_mode', native_enum=False), nullable=False),
    sa.Column('transaction_id', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('Success', 'Pending', 'Failed', name='payment_status', native_enum=False), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.invoice_id'], ),
    sa.PrimaryKeyConstraint('payment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('prescriptions')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_notification_logs_event'), table_name='notification_logs')
    op.drop_index(op.f('ix_notification_logs_created_at'), table_name='notification_logs')
    op.drop_table('notification_logs')
    op.drop_table('medicines')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_appointments_appt_date'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_principal_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_family_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_patients_unique_patient_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_mobile'), table_name='patients')
    op.drop_index(op.f('ix_patients_full_name'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_otp_codes_mobile'), table_name='otp_codes')
    op.drop_table('otp_codes')
    op.drop_table('clinics')
    # ### end Alembic commands ###
